# Generated by Django 3.0.3 on 2020-04-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('R', 'Rather_Not_Say')], max_length=6)),
                ('photo', models.ImageField(upload_to='profile_photos/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('emergency_contact1', models.CharField(blank=True, max_length=20)),
                ('emergency_contact2', models.CharField(blank=True, max_length=20)),
                ('employee_type', models.CharField(blank=True, choices=[('I', 'Intern'), ('E', 'Employe')], max_length=25)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=234)),
                ('name', models.CharField(default='apss_employee', max_length=234)),
                ('month', models.CharField(blank=True, default=None, max_length=234, null=True)),
                ('week_no', models.CharField(blank=True, default=None, max_length=234, null=True)),
                ('date', models.CharField(blank=True, default=None, max_length=234, null=True)),
                ('day', models.CharField(max_length=23)),
                ('lead_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('today_work_details', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('project', models.CharField(blank=True, default=None, max_length=237, null=True)),
                ('hours', models.CharField(blank=True, default=None, max_length=67, null=True)),
                ('login', models.CharField(blank=True, default=None, max_length=56, null=True)),
                ('logout', models.CharField(blank=True, default=None, max_length=53, null=True)),
                ('worklocationlogin', models.CharField(blank=True, choices=[('OF', 'Office'), ('H', 'Home')], default=None, max_length=53, null=True)),
                ('worklocationlogout', models.CharField(blank=True, choices=[('OF', 'Office'), ('H', 'Home')], default=None, max_length=53, null=True)),
                ('loginipaddress', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('logoutnipaddress', models.GenericIPAddressField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=60)),
                ('otp', models.CharField(blank=True, max_length=8)),
                ('date', models.CharField(blank=True, max_length=15)),
                ('time', models.CharField(blank=True, max_length=34)),
            ],
        ),
    ]
