# Generated by Django 3.0.4 on 2020-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200413_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='month',
            field=models.CharField(blank=True, max_length=19),
        ),
        migrations.AddField(
            model_name='otp',
            name='year',
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
