# Generated by Django 3.0.4 on 2020-04-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200428_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emergency_contact1_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact2_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
